### ISSUE TITLE
hello my problem

### ISSUE THREAD

**Issue by axen1** [CanineFang/Twitter-Bot#1]
PS C:\Users\bahad> & C:/Users/bahad/AppData/Local/Programs/Python/Python312/python.exe "c:/Users/bahad/import tweepy.py"
Traceback (most recent call last):
  File "c:\Users\bahad\import tweepy.py", line 22, in <module>
    for tweet in tweets:
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
           ^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\cursor.py", line 286, in next
    self.current_page = next(self.page_iterator)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
           ^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\cursor.py", line 167, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\api.py", line 33, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\api.py", line 1146, in search_tweets
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\bahad\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweepy\api.py", line 269, in request
    raise Unauthorized(resp)
tweepy.errors.Unauthorized: 401 Unauthorized
32 - Could not authenticate you.

**Comment by CanineFang** [comment]
Hello, I'm still trying to debug the issue. I will let you know when it's
fixed on the WhatsApp group

**Comment by axen1** [comment]
Hello again, can you add me to the WhatsApp group? And when will regulation be achieved?
